//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacroViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddImageAlb {
            get {
                object obj = ResourceManager.GetObject("AddImageAlb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddImageAlb2 {
            get {
                object obj = ResourceManager.GetObject("AddImageAlb2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table border=&apos;1&apos; style=&apos;font-size:32px;&apos;width=&apos;50%&apos;&gt;&lt;tr&gt;&lt;td&gt;&amp;#x1F600;&lt;/td&gt;&lt;td&gt;&amp;#x1F601;&lt;/td&gt;&lt;td&gt;&amp;#x1F602;&lt;/td&gt;&lt;td&gt;&amp;#x1F923;&lt;/td&gt;&lt;td&gt;&amp;#x1F603;&lt;/td&gt;&lt;td&gt;&amp;#x1F604;&lt;/td&gt;&lt;td&gt;&amp;#x1F605;&lt;/td&gt;&lt;td&gt;&amp;#x1F606;&lt;/td&gt;&lt;td&gt;&amp;#x1F609;&lt;/td&gt;&lt;td&gt;&amp;#x1F60A;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&amp;#x1F60B;&lt;/td&gt;&lt;td&gt;&amp;#x1F60E;&lt;/td&gt;&lt;td&gt;&amp;#x1F60D;&lt;/td&gt;&lt;td&gt;&amp;#x1F618;&lt;/td&gt;&lt;td&gt;&amp;#x1F617;&lt;/td&gt;&lt;td&gt;&amp;#x1F619;&lt;/td&gt;&lt;td&gt;&amp;#x1F61A;&lt;/td&gt;&lt;td&gt;&amp;#x263A;&lt;/td&gt;&lt;td&gt;&amp;#x1F642;&lt;/td&gt;&lt;td&gt;&amp;#x1F917;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&amp;#x1F914;&lt;/td&gt;&lt;td&gt;&amp;#x1F610;&lt;/td&gt;&lt;td&gt;&amp;#x1F611;&lt;/td&gt;&lt;td&gt;&amp;#x1F636;&lt;/td&gt;&lt;td&gt;&amp;# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table border=&apos;1&apos; width=&apos;100%&apos;&gt;&lt;tr&gt;&lt;td&gt;#A2M Iceland English &lt;/td&gt;&lt;td&gt;#ABN Norway&lt;/td&gt;&lt;td&gt;#AKG Eastern Europe&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;#A2N Saudi Arabia Arabic&apos;English &lt;/td&gt;&lt;td&gt;#ABP Swiss (German)&lt;/td&gt;&lt;td&gt;#AKJ Hebrew (English)&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;#A2Q Ukraine Ukrainian &lt;/td&gt;&lt;td&gt;#ABQ Swiss (French)&lt;/td&gt;&lt;td&gt;#AKL Thailand&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;#AB0 Taiwan&lt;/td&gt;&lt;td&gt;#ABS Sweden&lt;/td&gt;&lt;td&gt;#AKN Slovenia&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;#AB1 Korea&lt;/td&gt;&lt;td&gt;#ABT Hebrew&lt;/td&gt;&lt;td&gt;#AKQ Serbia Serbian &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;#AB2 China&lt;/td&gt;&lt;td&gt;#ABU UK (English)&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HP_CountryCodes {
            get {
                return ResourceManager.GetString("HP_CountryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is used by MacroViewer
        ///
        ///Number Countries:68
        ///
        ///Columns wanted:3
        ///
        ///Number Rows:23
        ///
        ///Number slots:69
        ///
        ///#A2M - Iceland - English 
        ///#A2N - Saudi Arabia - Arabic&apos;English 
        ///#A2Q - Ukraine - Ukrainian 
        ///#AB0 Taiwan
        ///#AB1 Korea
        ///#AB2 China
        ///#AB4 Singapore Malaysia
        ///#AB5 Hong Kong
        ///#AB6 Arabia (French)
        ///#AB7 Greece
        ///#AB8 Turkey
        ///#AB9 Portugal
        ///#ABA US (English)
        ///#ABB Europe (English)
        ///#ABC Canada (French)
        ///#ABD Germany
        ///#ABE Spain
        ///#ABF France
        ///#ABG Australia
        ///#ABH Netherlands
        ///#ABJ Japan
        ///#ABL Canada [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sorted_Raw_List {
            get {
                return ResourceManager.GetString("Sorted_Raw_List", resourceCulture);
            }
        }
    }
}
